FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY alembic ./alembic
COPY app ./app
COPY scripts ./scripts
COPY alembic.ini .
RUN chmod +x scripts/docker_start.sh

EXPOSE 8000

CMD ["sh", "scripts/docker_start.sh"]
